name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VER: 24.13
  CI: true

jobs:
  test-module:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Use Node.js ${{ env.NODE_VER }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VER }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test:typecheck && pnpm test

      - name: Lint and format
        run: pnpm lint && pnpm format:check
